---
title: 'Project 2: Modeling, Testing, and Predicting'
author: "SDS348"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later! In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(...) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in our project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is fine as long as you understand what the warnings mean.)</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables (ideally more!) that you want to use to build models/test hypotheses. At least one should be categorical (with 2-5 groups, ideally; definitely fewer than 10) and at least two should be numeric (taking on more than 10 distinct values). Ideally, at least of your variables will be binary (if not, you will have to create one by discretizing a numeric or collapsing levels of a categorical). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, I might encourage you to diversify things a bit and choose a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1 that you want to follow up with). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</li>
</ul>
<pre class="r"><code>games_4 = read_csv(&quot;games 4.csv&quot;)
deepblue &lt;- games_4 %&gt;% select(rated, turns, white_rating, black_rating,opening_ply)
deepblue &lt;- deepblue%&gt;% slice(1:100)</code></pre>
<p><em>The chess dataset contains data on games played on Lichess.org. The variable rated looks at whether the game was played between rated players or between amateur. White_Rating and Black_Rating measure the ELO ratings of both the white and black player in each game. Turns measures the total number of turns in the game and opening_ply measures the number of moves in the opening phase. The dataset is massive and many of the games are not helpful because one of the players resigned or the time ran out. This is why I selected for the 100 games most relevant to me. I chose this dataset because chess has been a lifelong love of mine. I started playing as a child with my dad and still play very frequently. It is considered the ultimate strategy game and so I'm curious to see how data supports the use of certain strategies as well as see how often a higher rating leads to victory.</em></p>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn't make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss MANOVA assumptions and whether or not they are likely to have been met (no need for anything too in-depth) (2).</li>
</ul>
<pre class="r"><code>library(rstatix)

group &lt;- deepblue$rated 
DVs &lt;- deepblue %&gt;% select(turns, opening_ply)
sapply(split(DVs,group), mshapiro_test)</code></pre>
<pre><code>##           FALSE       TRUE        
## statistic 0.9116594   0.8599991   
## p.value   0.007221099 3.351234e-06</code></pre>
<pre class="r"><code>box_m(DVs, group)</code></pre>
<pre><code>## # A tibble: 1 x 4
## statistic p.value parameter method
## &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;
## 1 30.1 0.00000134 3 Box&#39;s M-test for Homogeneity of
Covariance Matrices</code></pre>
<pre class="r"><code>lapply(split(DVs,group), cov)</code></pre>
<pre><code>## $`FALSE`
##                 turns opening_ply
## turns       508.49206    22.29683
## opening_ply  22.29683    18.06587
## 
## $`TRUE`
##                 turns opening_ply
## turns       653.59499  -10.121776
## opening_ply -10.12178    4.136657</code></pre>
<pre class="r"><code>man1&lt;-manova(cbind(turns,opening_ply)~rated, data= deepblue)
summary(man1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## rated 1 0.17309 10.152 2 97 9.925e-05 ***
## Residuals 98
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>## Response turns :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## rated 1 9642 9641.6 16.022 0.0001218 ***
## Residuals 98 58974 601.8
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response opening_ply :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## rated 1 37.93 37.925 4.1624 0.04402 *
## Residuals 98 892.91 9.111
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>deepblue%&gt;%group_by(rated)%&gt;%summarize(mean(turns),mean(opening_ply))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   rated `mean(turns)` `mean(opening_ply)`
##   &lt;lgl&gt;         &lt;dbl&gt;               &lt;dbl&gt;
## 1 FALSE          32.3                5.36
## 2 TRUE           52.7                4.08</code></pre>
<pre class="r"><code>pairwise.t.test(deepblue$turns, deepblue$rated, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  deepblue$turns and deepblue$rated 
## 
##      FALSE  
## TRUE 0.00012
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>.05/5</code></pre>
<pre><code>## [1] 0.01</code></pre>
<p><em>A one-way MANOVA was conducted to determine the effect of the rating status (TRUE, FALSE) on two dependent variables (turns and opening_ply). I did not include the white and black response variable because the existence of a rating automatically means the game is rated. Examination of bivariate density plots for each group revealed no stark deparures from multivariate normality. Examination of covariance matrices for each group revealed relative homogeneity. No univariate or multivariate outliers were evident and MANOVA was considered to be an appropriate analysis technique.Significant differences were found among the two rating statuses for at least one of the dependent variables. Univariate ANOVAs for each dependent variable were conducted as follow-up tests to the MANOVA, using the Bonferroni method for controlling Type I error rates for multiple comparisons. Only the univariate ANOVA for turns was significant after adjusting for the bonferonni correction.Post hoc analysis was performed conducting pairwise comparisons to determine which rating status differed in turns. The ratings TRUE and FALSE were found to differ significantly from each other in terms of only turns after adjusting for multiple comparisons (bonferroni). 5 total tests were performed (1 MANOVA, 2ANOVAS, and 2 t-tests.</em></p>
<ul>
<li><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ul>
<pre class="r"><code>summary(aov(turns~rated,data=deepblue))</code></pre>
<pre><code>## Df Sum Sq Mean Sq F value Pr(&gt;F)
## rated 1 9642 9642 16.02 0.000122 ***
## Residuals 98 58974 602
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>obs_F&lt;-4.162
Fs&lt;-replicate(5000,{
  new&lt;-deepblue%&gt;%mutate(turns=sample(turns))
  SSW&lt;- new%&gt;%group_by(rated)%&gt;%summarize(SSW=sum((turns-mean(turns))^2))%&gt;%
       summarize(sum(SSW))%&gt;%pull
  SSB&lt;- new%&gt;%mutate(mean=mean(turns))%&gt;%group_by(rated)%&gt;%mutate(groupmean=mean(turns))%&gt;%
       summarize(SSB=sum((mean-groupmean)^2))%&gt;%summarize(sum(SSB))%&gt;%pull
  (SSB/4)/(SSW/96)
})
hist(Fs, prob=T); abline(v = obs_F, col=&quot;red&quot;,add=T)</code></pre>
<p><img src="public/project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(Fs&gt;obs_F)</code></pre>
<pre><code>## [1] 0</code></pre>
<p><em>The null hypothesis is that the mean number of turns in the game will be the same whether the game is rated or not. The alternative hypothesis is that the number of turns between a rated and an unrated game will differ signficiantly. The p-value is far below the cutoff and so we reject the null hypothesis and conclude there is a difference between the groups. This can also be seen on the graph where all the generated F's are smaller than the actual F-statistic.</em></p>
<ul>
<li><p><strong>3. (35 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<ul>
<li>Interpret the coefficient estimates (do not discuss significance) (10)</li>
<li>Plot the regression using <code>ggplot()</code> using geom_smooth(method=&quot;lm&quot;). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the <code>interactions</code> package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (8)</li>
<li>Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (4)</li>
<li>Regardless, recompute regression results with robust standard errors via <code>coeftest(..., vcov=vcovHC(...))</code>. Discuss significance of results, including any changes from before/after robust SEs if applicable. (8)</li>
<li>What proportion of the variation in the outcome does your model explain? (4)</li>
</ul></li>
</ul>
<pre class="r"><code>deepblue$opening_ply_c &lt;- deepblue$opening_ply - mean(deepblue$opening_ply)
bluefit&lt;-lm(turns ~ opening_ply_c * rated, data=deepblue)
summary(bluefit)</code></pre>
<pre><code>##
## Call:
## lm(formula = turns ~ opening_ply_c * rated, data =
deepblue)
##
## Residuals:
## Min 1Q Median 3Q Max
## -52.372 -17.955 -1.096 10.682 80.521
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 31.2644 4.1184 7.591 2.06e-11 ***
## opening_ply_c 1.2342 0.9643 1.280 0.203691
## ratedTRUE 20.3399 5.1604 3.941 0.000154 ***
## opening_ply_c:ratedTRUE -3.6810 1.7850 -2.062 0.041892 *
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 24.25 on 96 degrees of freedom
## Multiple R-squared: 0.1773, Adjusted R-squared: 0.1516
## F-statistic: 6.896 on 3 and 96 DF, p-value: 0.0002964</code></pre>
<pre class="r"><code>ggplot(deepblue, aes(x=opening_ply_c, y=turns,group=rated))+geom_point(aes(color=rated))+
  geom_smooth(method=&quot;lm&quot;,formula=y~1,se=F,fullrange=T,aes(color=rated))+
theme(legend.position=c(.9,.70))+xlab(&quot;&quot;)</code></pre>
<p><img src="public/project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>resids&lt;-bluefit$residuals
fitvals&lt;-bluefit$fitted.values
library(ggplot2)
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="public/project/project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids))</code></pre>
<p><img src="public/project/project2_files/figure-html/unnamed-chunk-4-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(sandwich)
library(lmtest)
bptest(bluefit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  bluefit
## BP = 1.3662, df = 3, p-value = 0.7135</code></pre>
<pre class="r"><code>coeftest(bluefit, vcov = vcovHC(bluefit))[,1:4]</code></pre>
<pre><code>## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 31.264366 3.8847848 8.047902 2.249544e-12
## opening_ply_c 1.234196 0.7357069 1.677564 9.668521e-02
## ratedTRUE 20.339871 4.9656366 4.096125 8.772900e-05
## opening_ply_c:ratedTRUE -3.681045 1.3694411 -2.687991
8.474548e-03</code></pre>
<p><em>The intercept of 31.26 is the predicted number of turns for an unrated game with an average number of opening plays. The estimated effect slope of opening plays on turns for unrated games is 1.23. For games with an average number of opening plays, rated games have a predicted number of turns that is 20.34 greater than than unrated games. The difference in slopes between opening play and rating is 3.68. After recomputing with robust standard errors, opening play, rating, and the interaction of opening play and ratign are all significant. The main differnece is that after calculating robust standard errors the opening play is now a signifcant predictor of the number of turns. Lastly, the adjusted R-squared value of .1516 indicates that about 15.16% of the variation can be explained by the model. </em></p>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code>bluefit&lt;-lm(turns ~ opening_ply_c * rated, data=deepblue)
resids&lt;-bluefit$residuals 
fitted&lt;-bluefit$fitted.values
resid_resamp&lt;-replicate(5000,{
    new_resids&lt;-sample(resids,replace=TRUE) 
    deepblue$new_turns&lt;-fitted+new_resids 
    bluefit&lt;-lm(new_turns~ opening_ply_c * rated,data=deepblue) 
    coef(bluefit) 
})
resid_resamp%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>## (Intercept) opening_ply_c ratedTRUE
opening_ply_c:ratedTRUE
## 1 4.023141 0.9541289 5.153186 1.761515</code></pre>
<p><em>The bootstrapped SE' are all fairly close in value to both the normal and robust standard errors, but is slight closer to the original SE's.</em></p>
<ul>
<li><p><strong>5. (25 pts)</strong> Fit a logistic regression model predicting a binary variable (if you don't have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (2)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)</li>
<li>Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (3)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)</li>
</ul></li>
</ul>
<pre class="r"><code>library(tidyverse)
library(lmtest)
deepbluedata&lt;-deepblue%&gt;%mutate(y=ifelse(rated==&quot;TRUE&quot;,1,0))
fitdeepblue&lt;-glm(y~ turns + opening_ply_c,data=deepbluedata,family=binomial(link=&quot;logit&quot;))
coeftest(fitdeepblue)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -1.059051 0.490184 -2.1605 0.0307326 *
## turns 0.040064 0.011427 3.5061 0.0004547 ***
## opening_ply_c -0.137072 0.073775 -1.8580 0.0631730 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fitdeepblue))</code></pre>
<pre><code>##   (Intercept)         turns opening_ply_c 
##     0.3467847     1.0408773     0.8719075</code></pre>
<pre class="r"><code>prob&lt;-predict(fitdeepblue,type=&quot;response&quot;) 
pred&lt;-ifelse(prob&gt;.5,1,0)
table(prediction=pred, truth=deepbluedata$y)%&gt;%addmargins</code></pre>
<pre><code>##           truth
## prediction   0   1 Sum
##        0    19  13  32
##        1    17  51  68
##        Sum  36  64 100</code></pre>
<pre class="r"><code>class_diag &lt;- function(probs,truth){
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  f1=2*(sens*ppv)/(sens+ppv)
  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  TPR=cumsum(truth)/max(1,sum(truth))
  FPR=cumsum(!truth)/max(1,sum(!truth))
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
  data.frame(acc,sens,spec,ppv,f1,auc)
}
class_diag(prob,deepbluedata$y)</code></pre>
<pre><code>##   acc     sens      spec  ppv        f1       auc
## 1 0.7 0.796875 0.5277778 0.75 0.7727273 0.7682292</code></pre>
<pre class="r"><code>deepbluedata$logit&lt;-predict(fitdeepblue,type=&quot;link&quot;)
deepbluedata%&gt;%ggplot(aes(logit,fill=rated))+geom_density(alpha=.4)+
  theme(legend.position=c(.5,.5))+geom_vline(xintercept=0)+xlab(&quot;predictor (logit)&quot;)</code></pre>
<p><img src="public/project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC)
ROCplot&lt;-ggplot(deepbluedata)+geom_roc(aes(d=y,m=prob), n.cuts=0)
ROCplot</code></pre>
<p><img src="public/project/project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.7682292</code></pre>
<p><em>The odds of playing in a rate game are 0.347 when there are 0 turns and 0 opening plays. Controlling for opening plays, for every 1 additional number of turns, the odds of playing in a rated game increase by 1.041. Controlling for turns, for every 1 play increase in opening plays the odds of playing in a rated game changed by a factor of 0.872. The model has an accuracy of 0.7. The true positive rate, or proportion of rated games correctly classified is 0.797. The true negative rate, or proprotion of unrated games correctly classified, was much lower at a value of 0.528. The proportion classified as rated that actually were was 0.75. The AUC calculated from the plot and found in the classification diagnostics returned a value of 0.768 which indicates the model does a fair job of predicting values.</em></p>
<ul>
<li><p><strong>6. (25 pts)</strong> Perform a logistic regression predicting the same binary response variable from <em>ALL</em> of the rest of your variables (the more, the better!)</p>
<ul>
<li>Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)</li>
<li>Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)</li>
<li>Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. (5)</li>
<li>Perform 10-fold CV using only the variables lasso selected: compare model's out-of-sample AUC to that of your logistic regressions above (5)</li>
</ul></li>
</ul>
<pre class="r"><code>bluefitbaby&lt;-glm(rated~ turns + opening_ply_c + white_rating + black_rating,data=deepbluedata,family=binomial(link=&quot;logit&quot;))
prob1&lt;-predict(bluefitbaby,type=&quot;response&quot;)
class_diag(prob1,deepbluedata$rated)</code></pre>
<pre><code>## acc sens spec ppv f1 auc
## TRUE 0.77 0.828125 0.6666667 0.8153846 0.8217054
0.8255208</code></pre>
<pre class="r"><code>set.seed(1234)
k=10
data &lt;- deepbluedata %&gt;% sample_frac
folds &lt;- ntile(1:nrow(data),n=10)
diags&lt;-NULL
for(i in 1:k){
  train &lt;- data[folds!=i,] 
  test &lt;- data[folds==i,] 
  truth &lt;- test$rated 
  bluefit &lt;- glm(rated~ (turns + opening_ply_c + white_rating + black_rating)^2, data=train, family=&quot;binomial&quot;)
  probs &lt;- predict(bluefit, newdata=test, type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean)</code></pre>
<pre><code>##    acc      sens      spec       ppv        f1       auc
## 1 0.72 0.7755952 0.5983333 0.7692857 0.7666743 0.7451071</code></pre>
<pre class="r"><code>library(glmnet)
y&lt;-as.matrix(deepbluedata$y)
x &lt;- model.matrix(bluefitbaby)
cv &lt;- cv.glmnet(x,y, family=&quot;binomial&quot;)
lasso&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 6 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                         s0
## (Intercept)   -0.857171689
## (Intercept)    .          
## turns          0.007177409
## opening_ply_c  .          
## white_rating   .          
## black_rating   0.000812685</code></pre>
<pre class="r"><code>set.seed(1234)
k=10
data &lt;- deepbluedata %&gt;% sample_frac 
folds &lt;- ntile(1:nrow(data),n=10)
diags&lt;-NULL
for(i in 1:k){
  train &lt;- data[folds!=i,] 
  test &lt;- data[folds==i,] 
  truth &lt;- test$rated
  bluefit &lt;- glm(rated~ (turns + black_rating)^2, 
                 data=train, family=&quot;binomial&quot;)
  probs &lt;- predict(bluefit, newdata=test, type=&quot;response&quot;)
  diags&lt;-rbind(diags,class_diag(probs,truth))
}
diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##    acc      sens      spec       ppv        f1       auc
## 1 0.77 0.8229762 0.5683333 0.8065476 0.8084305 0.7825595</code></pre>
<p><em>The model has an accuracy of 0.77. The true positive rate, or proportion of rated games correctly classified is 0.828. The true negative rate, or proprotion of unrated games correctly classified, was much lower at a value of 0.667. The proportion classified as rated that actually were was 0.815. The AUC, or overall predictive ability of the model is 0.8255. This AUC is considered good. The out of sample diagnostics has an AUC of 0.74. This AUC is 0.74. While this is still a fair AUC value, it is below the in sample AUC and so we can say the model was overfitted. After performing LASSO on the data, the variables turns and black_rating were most predictive and so will be retained. After using only the relevant predictors from LASSO, an AUC of 0.783 was found. This AUC was higher than the AUC calculated from the 10 fold CV.</em></p>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn't end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much... To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don't have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>. Run <code>install.packages(&quot;fivethirtyeight&quot;),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>...</p>
</div>
</div>
</div>
